### ISSUE TITLE
win_chocolatey_feature does not support when

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-ansible#105]
### What You Are Seeing?

Trying to use `when` conditionals to set Chocolatey features, and it appears the module does not support them

### What is Expected?

The feature is set to the correct state when the condition matches

### How Did You Get This To Happen? (Steps to Reproduce)

1. Create playbook that uses a `when` condition
2. Sync the project in AAP
3. Execute task from Template
4. Observe the error

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): Server 2019
* Windows PowerShell version (Run: `$PSVersionTable`): 5.1
* Chocolatey version (Run `choco --version`): 1.1.0

### Output Log

```json
{
  "changed": false,
  "msg": "Unsupported parameters for (win_chocolatey_feature) module: when. Supported parameters include: state, name",
  "invocation": {
    "module_args": {
      "when": "ansible_facts[\"allowGlobalConfirmation\"] != \"disabled\"",
      "state": "disabled",
      "name": "allowGlobalConfirmation"
    }
  },
  "_ansible_no_log": null,
  "item": "allowGlobalConfirmation",
  "ansible_loop_var": "item",
  "_ansible_item_label": "allowGlobalConfirmation"
}
```

**Comment by steviecoaster** [comment]
Here is a sample playbook you can use to observe the behavior:

```yaml
---
 
- name: Install and Configure Chocolatey
  hosts: all

  tasks:
  - name: Gather facts from chocolatey
    win_chocolatey_facts:
   - name: Displays the Configuration
    debug:
      var: ansible_chocolatey.config

  - name: Displays the Feature
    debug:
      var: ansible_chocolatey.feature

  - name: Displays the Sources
    debug:
      var: ansible_chocolatey.sources

   - name: Disable required features
    win_chocolatey_feature:
      name: "{{ item }}"
      state: disabled
      when: ansible_facts["{{ item }}"] != "disabled"
    loop:
      - allowGlobalConfirmation
      - failOnStandardError
      - allowEmptyChecksums
      - logEnvironmentValues
      - virusCheck
      - useEnhancedExitCodes
      - exitOnRebootDetected
      - useFipsCompliantChecksums
      - useRememberedArgumentsForUpgrades
      - ignoreUnfoundPackagesOnUpgradeOutdated
      - logWithoutColor
      - disableCompatibilityChecks
      - reduceOnlyNupkgSize
      - useBackgroundService
      - useBackgroundServiceWithNonAdministratorsOnly
      - useBackgroundServiceInteractively
      - allowBackgroundServiceUninstallsFromUserInstallsOnly
      - showAllPackagesInProgramsAndFeatures
      - adminOnlyExecutionForAllChocolateyCommands
      - adminOnlyExecutionForNewCommand
      - adminOnlyExecutionForDownloadCommand
      - useChocolateyCentralManagement
      - useChocolateyCentralManagementDeployments
      - allowPreviewFeatures    
```

**Comment by JPRuskin** [comment]
I think we've found the issue here - as we've created a follow-up issue for improving performance of the module (#108), we can probably close this off?

**Comment by pauby** [comment]
I'm a little bit rusty with Ansible now, but I don't think `when` is in the correct place there. Your passing it as an argument to the module, and it's not an argument the module accepts. `when` is a conditional which is evaluated by Ansible and not the module. So Ansible will evaluate the condition and execute the code if it's `true` and skip if it's false.

I'm also unsure of what you're trying to do here. You're disabling items that are not already disabled. You don't need to check. Ansible is idempotent, so if it's already disabled, it won't do anything:

```
   - name: "Disable required features"
    win_chocolatey_feature:
      name: "{{ item }}"
      state: disabled
    loop:
      - "allowGlobalConfirmation"
      - "failOnStandardError"
      - "allowEmptyChecksums"
      - "logEnvironmentValues"
      - "virusCheck"
...
```

I've added the quotes around some parts for no reason other than it's good practice. 

If you really wanted to do what you're suggesting, this should work (not my comment about being rusty, but I've looked at old code I use and it's this format):

```
   - name: Disable required features
    win_chocolatey_feature:
      name: "{{ item }}"
      state: disabled
    loop:
      - allowGlobalConfirmation
      - failOnStandardError
      - allowEmptyChecksums
      - logEnvironmentValues
      - virusCheck
    when: (ansible_facts["{{ item }}"] != "disabled")
...
```

I added brackets around the `when` condition just because it's fixed issues for me in the past, especially where you have multiple conditions chained. So, I just do it everywhere, so I don't forget.
