### ISSUE TITLE
Increase efficiency of fact gathering using the win_chocolatey_facts module

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-ansible#108]
Currently, the win_chocolatey_facts module gathers the following items:

- config
- features
- sources
- packages
- outdated

This causes a large performance hit to fact gathering, especially running `choco oudated` every single time, particularly on hosts with a large number of Chocolatey packages installed.

Ansible has added the concept of a _subset_ of facts to collect during gathering, which you can control with filters. Examples of this can be found in their documentation available [here](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html#examples).

I propose that in our win_chocolatey.facts module we provide the same mechanism such that we could do something similar to the following:

```yaml
- name: Gather facts
  win_chocolatey_facts:
    gather_subset:
    - config
    - features
    - sources
    - !packages
    - !outdated
```
   
The example above would _only_ gather the facts for config, features, sources.
