### ISSUE TITLE
win_chocolatey - Installation of Chocolatey CLI v2.0.0+ fails when .NET Framework 4.8 dependency not met

### ISSUE THREAD

**Issue by Windos** [chocolatey/chocolatey-ansible#120]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

When using the `win_chocolatey` module to install Chocolatey CLI v2.0.0 or above on a system without .NET Framework 4.8 installed, the task will fail with an error stating that the .NET Framework has been installed and that a restart is required. After the reboot, the Chocolatey CLI install can be re-attempted and will succeed.

### What is Expected?

The `win_chocolatey` module helpfully bootstraps Chocolatey CLI if it is not already installed, but this is now only possible if .NET Framework 4.8 is already present on the system.

The module should better handle the situation where this dependency is not already satisfied. The question at the moment is how?

The module probably shouldn't perform the reboot (if it even technically can), so it may be required to pre-check the requirement if installing Chocolatey CLI v2.0.0 or above and error earlier (and more specifically) about the dependency requirement.

### How Did You Get This To Happen?

Use a system that does not have .NET Framework 4.8 pre-installed, such as Windows Server 2016 or 2019.

Run the following Ansible playbook against it:

```yaml
---
- hosts: 'test2016' # Replace with actual test target
  gather_facts: true

  tasks:
    - name: Install Chocolatey
      win_chocolatey:
        name: chocolatey
        state: present
...
```

See the following output:

![Example error output](https://github.com/chocolatey/chocolatey-ansible/assets/6955786/6ba998ac-a42f-487b-86a8-92a18c394016)

At this point you can reboot the test target and re-run the playbook and Chocolatey CLI v2.0.0 and above will install successfully.

### System Details

My test machine was:

* Operating System: 10.0.14393.0
* Windows PowerShell version: 5.1.14393.693
* Chocolatey CLI Version: N/A
* Chocolatey Licensed Extension version: N/A
* Chocolatey License type: N/A
* Terminal/Emulator: Windows PowerShell

### Installed Packages

```bash
N/A
```

### Output Log

```bash
N/A
```

### Additional Context

There are a couple of work arounds using the win_chocolatey module as is today in order to complete the Chocolatey CLI v2.0.0 upgrade.

First, specifically install Chocolatey CLI v1.4.0, install .NET Framework 4.8, reboot, and finally upgrade Chocolatey CLI:

```yaml
    - name: Install Chocolatey 1.4.0
      win_chocolatey:
        name: chocolatey
        state: present
        version: 1.4.0

    - name: Install Microsoft .NET Framework 4.8
      win_chocolatey:
        name: netfx-4.8
        state: present
      register: _framework_install

    - ansible.windows.win_reboot:
      when: _framework_install is changed

    - name: Upgrade to latest Chocolatey
      win_chocolatey:
        name: chocolatey
        state: latest
```

Another option is to try for the Chocolatey CLI install and ignore the error message (actually use the failure as the trigger for performing a reboot):

```yaml
    - name: Install Chocolatey
      win_chocolatey:
        name: chocolatey
        state: present
      register: _choco_install
      ignore_errors: true

    - ansible.windows.win_reboot:
      when: _choco_install is failed

    - name: Install Chocolatey
      win_chocolatey:
        name: chocolatey
        state: present
      when: _choco_install is failed
```
