### ISSUE TITLE
NET Framework check still triggers/fails when installing Chocolatey using chocolateyDownloadUrl

### ISSUE THREAD

**Issue by ch0nx** [chocolatey/chocolatey-ansible#136]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

When using the 'chocolateyDownloadUrl' environment variable to target a specific chocolatey package (below 2.x in this case), the .NET framework check defined [here](https://github.com/chocolatey/chocolatey-ansible/blob/9bdc0d40437a7dc7f0181af42da7e35bbcfcae4a/chocolatey/plugins/module_utils/Packages.psm1#L1081C1-L1099C10) still triggers since it isnt specifying an exact version.  

However the [bootstrap script](https://community.chocolatey.org/install.ps1) from Chocolatey that is invoked by default will IGNORE the download url variable if the version is specified, so this check cannot be circumvented.

### What is Expected?

Using the chocolateyDownloadUrl env variable should prevent the .NET check from triggering, since it implies a specific version is being targeted.

### How Did You Get This To Happen?

1. Install Chocolatey from a specific source using the following:
```
- name: Install chocolatey from source
      chocolatey.chocolatey.win_chocolatey:
        name: chocolatey
        state: present
      environment:
        chocolateyDownloadUrl: "https://myvery.specialfeed.int/chocolatey.1.3.1.nupkg"
```

### System Details

* Operating System: Ubuntu 22.04 
* Windows PowerShell version:  7.2.7
* Chocolatey CLI Version: 1.3.1 targeted
* Chocolatey Licensed Extension version: n/a
* Chocolatey License type: n/a
* Terminal/Emulator: n/a

### Installed Packages

```bash
No additional packages are being installed since this is the actual Chocolatey installation
```

### Output Log

```bash
fatal: [default]: FAILED! => {"changed": false, "command": "", "msg": "Chocolatey 2.0.0 requires .NET Framework 4.8 or higher to be installed. Please install .NET Framework 4.8 or higher and try again, or specify a 1.x version of Chocolatey to install.", "rc": 0}
```
