### ISSUE TITLE
Add a mode that lets us set the version and will upgrade or downgrade without forcing the installation

### ISSUE THREAD

**Issue by rgl** [chocolatey/chocolatey-ansible#143]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

I want to use Ansible to set the desirable state of specific package version. And have this module install, upgrade or downgrade iif the installed version is not the one I set. I do not want to use `force: true` because that would unnecessary reinstall the package every time.

### Describe The Solution. Why is it needed?

```yaml
- name: Install Inkscape
  chocolatey.chocolatey.win_chocolatey:
    # https://community.chocolatey.org/packages/inkscape
    name: inkscape
    # renovate: datasource=nuget:chocolatey depName=inkscape
    version: '1.3.1'
    state: upgrade-or-downgrade
```

or, have extra flags like:

```yaml
- name: Install Inkscape
  chocolatey.chocolatey.win_chocolatey:
    # https://community.chocolatey.org/packages/inkscape
    name: inkscape
    # renovate: datasource=nuget:chocolatey depName=inkscape
    version: '1.3.1'
    state: present
    allow_upgrade: true
    allow_downgrade: true
```
