### ISSUE TITLE
Package parameters not taken into account

### ISSUE THREAD

**Issue by mathstuf** [chocolatey/chocolatey-ansible#146]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

I have a set of Ansible rules that build up a string for `package_params`. If this changes, the package is not prodded to analyze the parameters again. For example, I build up the set of `--add` flags for `visualstudio2022community`. If I deploy once with one set of `--add` flags, further deployments with additional `--add` flags do not end up adding those components to the existing installation.

### What is Expected?

Package parameters changing cause the new state to be realized.

### How Did You Get This To Happen?

```yaml
---
- name: 'Prepare key Visual Studio variable'
  ansible.builtin.set_fact:
    vs_year: '{{ item | replace("vs", "") }}'

- name: 'Prepare architecture variable (Intel)'
  ansible.builtin.set_fact:
    vs_arch: 'x86.x64'
  when: 'ansible_machine == "x86_64"'

- name: 'Prepare architecture variable (Intel)'
  ansible.builtin.set_fact:
    vs_arch: 'ARM64'
  when: 'ansible_machine == "arm64"'

- name: 'Build Visual Studio C++ component arguments'
  ansible.builtin.set_fact:
    vs_args: >-
      {{ vs_args | default("") }}
      --add Microsoft.VisualStudio.Component.VC.{{ toolchain }}.{{ vs_arch | mandatory }}
      --add Microsoft.VisualStudio.Component.VC.{{ toolchain }}.CLI.Support
      --add Microsoft.VisualStudio.Component.VC.{{ toolchain }}.MFC
  loop: '{{ software[item].cpp }}'
  loop_control:
    loop_var: 'toolchain'

- name: 'Build Visual Studio Windows SDK'
  ansible.builtin.set_fact:
    vs_args: >-
      {{ vs_args | default("") }}
      --add Microsoft.VisualStudio.Component.Windows11SDK.22621
      --add Microsoft.VisualStudio.Component.VC.Tools.{{ vs_arch | mandatory }}
      --add Microsoft.VisualStudio.Component.VC.CLI.Support
      --add Microsoft.VisualStudio.Component.VC.ATLMFC
  when: 'software[item].cpp is defined'

- name: 'Install Visual Studio {{ vs_year }}'
  chocolatey.chocolatey.win_chocolatey:
    name: 'visualstudio{{ vs_year }}community'
    package_params: '{{ vs_args | mandatory }}'
    state: latest
```

### System Details

* Operating System: Windows 10
* Windows PowerShell version: 5.1.19041.4170
* Chocolatey CLI Version: 2.2.2
* Chocolatey Licensed Extension version: N/A
* Chocolatey License type: Community
* Terminal/Emulator: cmd

### Installed Packages

```bash
Chocolatey v2.2.2
chocolatey 2.2.2
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1     
chocolatey-visualstudio.extension 1.11.1
dotnetfx 4.8.0.20220524
git 2.44.0
git.install 2.44.0
KB2919355 1.0.20160915
KB2919442 1.0.20160915
visualstudio2022community 117.9.5
visualstudio-installer 2.0.3     
12 packages installed.
```

### Output Log

```bash
https://gist.github.com/mathstuf/9649614a99964e3057449e79f3e3a20b
```
