### ISSUE TITLE
win_chocolatey ... pinned: yes hangs

### ISSUE THREAD

**Issue by basictheprogram** [chocolatey/chocolatey-ansible#16]
Open this at https://github.com/ansible/ansible/issues/69663 and was told to open the issue here.

##### SUMMARY
Trying to pin a package using name and version and the process hangs

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_chocolatey

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.9.9.post0
  config file = None
  configured module search path = ['/Users/tanner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/py3-ansible/src/ansible/lib/ansible
  executable location = /Users/tanner/projects/py3-ansible/src/ansible/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:28:52) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### OS / ENVIRONMENT
Ansible management host
  * ProductName:	Mac OS X
  * ProductVersion:	10.14.6
  * BuildVersion:	18G4032

Manage host
  * Windows 10 Professional
  
##### STEPS TO REPRODUCE

```yaml
- name: pin packages
  win_chocolatey:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
    pinned: yes
  when:
    - chocolatey_packages_pinned is defined
  ignore_errors: yes
  loop: "{{ chocolatey_packages_pinned|flatten(levels=1) }}"
```
##### EXPECTED RESULTS
Packages listed int the chocolatey_package_pinned list are pinned by chocolatey

##### ACTUAL RESULTS
Process just hangs

`ansible-playbook -i test ../chocolatey.yml -vvvv`
```paste below
TASK [win_chocolatey : debug] **************************************************
task path: /Users/tanner/projects/py3-ansible/src/playbooks.git/roles/win_chocolatey/tasks/main.yml:34
ok: [PC106.xxx.test] => {
    "msg": [
        {
            "name": "draftsight",
            "version": "2019.03.0.20190120"
        }
    ]
}

TASK [win_chocolatey : pin packages] *******************************************
task path: /Users/tanner/projects/py3-ansible/src/playbooks.git/roles/win_chocolatey/tasks/main.yml:46
Using module file /Users/tanner/projects/py3-ansible/src/ansible/lib/ansible/modules/windows/win_chocolatey.ps1
Pipelining is enabled.
<PC106.xxx.test> ESTABLISH WINRM CONNECTION FOR USER: Administrator@xxx.test on PORT 5986 TO PC106.xxx.test
EXEC (via pipeline wrapper)
```

**Comment by vexx32** [comment]
Thanks for confirming!

I'll have a look at what we're doing in the module here to see what's going awry. 🙂

**Comment by vexx32** [comment]
The pinning is done here:
https://github.com/chocolatey/chocolatey-ansible/blob/1fdb156ae9932bb7437da8b86ed1aded8009175b/chocolatey/plugins/modules/win_chocolatey.ps1#L430-L464

I suspect the issue might be that we're adding common arguments that we perhaps should not be adding (e.g., `--yes`, `--limit-output`, `--no-progress`) when we're doing pins.

May need to refactor the function used to sort out those arguments / snip that out entirely.

**Comment by vexx32** [comment]
Marking up for grabs for now in case yourself or others want to check it out, but we'll circle back and sort out a fix as time allows. We'll need to add tests for this too.

**Comment by vexx32** [comment]
I attempted to reproduce this with the VMs defined in the vagrantfile in the `testing-chocolatey` folder and I'm not seeing this issue.

The playbook I attempted to run is fairly straightforward:
```yml
---

- name: Run troublesome choco command
  gather_facts: false
  hosts: all

  tasks:
    - name: Install and pin a package
      chocolatey.chocolatey.win_chocolatey:
        name: python
        version: 3.9.5
        state: present
        pinned: yes
```

This is with ansible `2.10.9` and the most recent version of this collection installed. Can you please try to reproduce this in your environment with the latest version of the collection and see if the issue has been resolved in the meantime?
