### ISSUE TITLE
Use of 'version' borks register

### ISSUE THREAD

**Issue by ncook-hxgn** [chocolatey/chocolatey-ansible#174]
### Checklist

- [x] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [x] I have verified this is the correct repository for opening this issue.
- [x] I have verified no other issues exist related to my problem.
- [x] I have verified this is not an issue for a specific package.
- [x] I have verified this issue is not security related.
- [x] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Consider the following playbook snippet (this is from a role in a private collection, but I will simplify)

```yaml
- name: Install Python v{{ python_version }}
  win_chocolatey:
    name: python3
    version: '{{ python_version }}'
    state: present
  register: python_install
  when: python_version is defined

- name: Install Python
  win_chocolatey:
    name: python3
    state: latest
  register: python_install
  when: python_version is undefined

- name: Reboot if necessary
  ansible.windows.win_reboot:
  when: python_install.rc == 3010
```

I can make this playbook fail by setting `python_version` to something valid like `'3.13.3'` in my inventory file (which is at time of writing, the [latest non-prerelease python3 on chocolatey.org](https://community.chocolatey.org/packages/python3/3.13.1#versionhistory)).

What happens, is that the dictionary created by register appears to be empty, or at least not contain an `rc` object:

```log
2025-02-12T12:19:55Z:     azure-arm.imagebuild: fatal: [default]: FAILED! => {"msg": "The conditional check 'python_install.rc == 3010' failed. The error was: error while evaluating conditional (python_install.rc == 3010): 'dict object' has no attribute 'rc'\n\nThe error appears to be in '/home/vsts_azpcontainer/.ansible/collections/ansible_collections/mycollection/stuff/roles/python/tasks/main.yml': line 16, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Reboot if necessary\n  ^ here\n"}
```

I can also reproduce this targeting the nodejs-lts choco package, so I don't think it's related to the python3 package.

```yaml
- name: Install NodeJS v{{ nodejs_version }}
  win_chocolatey: 
    name: '{{ nodejs_name }}'
    version: '{{ nodejs_version }}'
    state: present
  register: nodejs_install
  when: nodejs_version is defined

- name: Install NodeJS
  win_chocolatey: 
    name: '{{ nodejs_name }}'
    state: latest
  register: nodejs_install
  when: nodejs_version is undefined
  
- name: Reboot if necessary
  ansible.windows.win_reboot:
  when: nodejs_install.rc == 3010
```

```log
2025-02-12T13:40:48Z:     azure-arm.imagebuild: fatal: [default]: FAILED! => {
2025-02-12T13:40:48Z:     azure-arm.imagebuild:     "msg": "The conditional check 'nodejs_install.rc == 3010' failed. The error was: error while evaluating conditional (nodejs_install.rc == 3010): 'dict object' has no attribute 'rc'\n\nThe error appears to be in '/home/vsts_azpcontainer/.ansible/collections/ansible_collections/mycollection/stuff/roles/nodejs/tasks/main.yml': line 16, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Reboot if necessary\n  ^ here\n"
2025-02-12T13:40:48Z:     azure-arm.imagebuild: }
```

### What is Expected?

Whether I pass a version to `win_chocolatey` or not, register should provide the return value for `rc`, as documented [here](https://docs.ansible.com/ansible/latest/collections/chocolatey/chocolatey/win_chocolatey_module.html#return-values)

### How Did You Get This To Happen?

simplest repro playbook snippet:

```yaml
- name: Install NodeJS v22.14.0
  win_chocolatey: 
    name: 'nodejs-lts'
    version: '22.14.0'
    state: present
  register: nodejs_install
  when: nodejs_version is defined
  
- name: Reboot if necessary
  ansible.windows.win_reboot:
  when: nodejs_install.rc == 3010
```

... choco is installed by us calling choco, we don't have a verbatim task to install choco. We presume it is the latest version:

```log
2025-02-12T12:18:25Z:     azure-arm.imagebuild: TASK [Gathering Facts] *********************************************************
2025-02-12T12:18:34Z:     azure-arm.imagebuild: ok: [default]
2025-02-12T12:18:34Z:     azure-arm.imagebuild:
2025-02-12T12:18:34Z:     azure-arm.imagebuild: TASK [mycollection.python : Install Python v3.13.1] ***********
2025-02-12T12:19:55Z:     azure-arm.imagebuild: [WARNING]: Chocolatey was missing from this system, so it was installed during
2025-02-12T12:19:55Z:     azure-arm.imagebuild: this task run.
2025-02-12T12:19:55Z:     azure-arm.imagebuild: changed: [default]
```

### System Details

* Operating System: Latest Windows Server 2022
* Windows PowerShell version: PS 5.1 (OOTB)
* * Chocolatey CLI Version: presume latest, automatically installed by win_chocolatey
* Chocolatey Licensed Extension version: N/A
* Chocolatey License type: Community
* Terminal/Emulator: Azure DevOps Pipeline/PowerShell

### Installed Packages

```bash
In reproducing this, only python3 and nodejs-lts were installed. Python brings a lot of vc runtimes..
```

### Output Log

```bash
somewhat confected:

2025-02-12T12:18:25Z:     azure-arm.imagebuild: TASK [Gathering Facts] *********************************************************
2025-02-12T12:18:34Z:     azure-arm.imagebuild: ok: [default]
2025-02-12T12:18:34Z:     azure-arm.imagebuild:
2025-02-12T12:18:34Z:     azure-arm.imagebuild: TASK [mycollection.python : Install Python v3.13.1] ***********
2025-02-12T12:19:55Z:     azure-arm.imagebuild: [WARNING]: Chocolatey was missing from this system, so it was installed during
2025-02-12T12:19:55Z:     azure-arm.imagebuild: this task run.
2025-02-12T12:19:55Z:     azure-arm.imagebuild: changed: [default]

...

2025-02-12T13:40:48Z:     azure-arm.imagebuild: fatal: [default]: FAILED! => {
2025-02-12T13:40:48Z:     azure-arm.imagebuild:     "msg": "The conditional check 'nodejs_install.rc == 3010' failed. The error was: error while evaluating conditional (nodejs_install.rc == 3010): 'dict object' has no attribute 'rc'\n\nThe error appears to be in '/home/vsts_azpcontainer/.ansible/collections/ansible_collections/mycollection/stuff/roles/nodejs/tasks/main.yml': line 16, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Reboot if necessary\n  ^ here\n"
2025-02-12T13:40:48Z:     azure-arm.imagebuild: }
```

**Comment by Windos** [comment]
What you're seeing here a quirk in how Ansible works and not a bug in this collection.

In short, Ansible registers the output of the task to the specified variable even if the task is skipped (this is so that you can take action based on the fact that a given task was skipped, if desired).

Using the [debug module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html) you can prove this out by inspecting the contents of your variable and if it is the same as what you expect it to be.

For example, take this example playbook:
```yaml
---
- name: 'Version defined - conditional tasks'
  hosts: vm
  gather_facts: true
  vars:
    python_version: 3.13.1

  tasks:
    - name: Install Python v{{ python_version }}
      win_chocolatey:
        name: python3
        version: '{{ python_version }}'
        state: present
      register: python_install
      when: python_version is defined

    - name: Inspect Registered Variables
      debug:
        var: python_install

    - name: Install Python
      win_chocolatey:
        name: python3
        state: latest
      register: python_install
      when: python_version is undefined

    - name: Inspect Registered Variables
      debug:
        var: python_install
...
```

The output of which in my testing is:

```ansible
PLAY [Version defined - conditional tasks] *****************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [vm]

TASK [Install Python v3.13.1] ******************************************************************************************
[WARNING]: Chocolatey was missing from this system, so it was installed during this task run.
changed: [vm]

TASK [Inspect Registered Variables] ************************************************************************************
ok: [vm] => {
    "python_install": {
        "changed": true,
        "choco_cli_version": "2.4.2",
        "failed": false,
        "rc": 0,
        "warnings": [
            "Chocolatey was missing from this system, so it was installed during this task run."
        ]
    }
}

TASK [Install Python] **************************************************************************************************
skipping: [vm]

TASK [Inspect Registered Variables] ************************************************************************************
ok: [vm] => {
    "python_install": {
        "changed": false,
        "false_condition": "python_version is undefined",
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}

PLAY RECAP *************************************************************************************************************
vm                         : ok=4    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```

As you can see the contents of the variable is what you expect straight after the install, but then the non-versioned task is skipped and overwrites the variable.

A couple of things you can do here.

In general, if you have tasks that may require a service to restart or indeed the entire host, then it's generally better to use "[handlers](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_handlers.html)", these are tasks that don't sit in the general flow of a play but can be "notified" that they need to run. Generally this happens at the end of the play, but you can "flush" them so that they execute at a desire point in a play.

Unfortunately, I'm not sure off hand how to combine both a handler and the condition that it only fire given a specific return code.

In this specific case, you can also consider only having the one `win_chocolatey` task that works regardless of if a version is passed or not. I personally use a task that looks a little something like this:

```yaml
- name: 'Install desired Chocolatey packages'
  chocolatey.chocolatey.win_chocolatey:
    name: '{{ item.name | mandatory  }}'
    version: '{{ item.version | default(omit) }}'
    state: '{{ "latest" if package_version is undefined else "downgrade" }}'
    package_params: '{{ item.package_params | default(omit) }}'
  loop: '{{ choco_packages }}'
```

This allows me to list all packages to install in my inventory along with a specific version if needed as well as and package parameters that the install may need. One note is that I set the state to `downgrade` if a version is specified, this means that I can specify a version lower than what may already be installed and the request will be honored (otherwise you'll get something like "installed version newer").

For completeness, my inventory then has this in it:

```yaml
choco_packages:
  - name: 'python3'
    version: '3.13.1'
  - name: 'nodejs-lts'
```

Apologies for the wall of text here. I wanted to give you something a little more actionable than a "it's not us."
