### ISSUE TITLE
win_chocolatey does not update env path

### ISSUE THREAD

**Issue by gamethis** [chocolatey/chocolatey-ansible#22]
When installing chocolately with win_chocolatey
It does not update the path which causes subsequent chocolatey configs to fails with the error
`Failed to find Chocolatey installation, make sure choco.exe is in the PATH env value`

Playbook sample
```
- name: Ensure chocolatey is installed with proxy
  win_chocolatey:
    name: chocolatey
    state: latest
    proxy_url: "{{ proxy_addr }}"
  register: choco_state_proxy
  when: proxy_addr is defined

- name: Disable the default public source
  win_chocolatey_source:
    name: chocolatey
    state: disabled
    source: https://chocolatey.org/api/v2
```

Output from log 
```
windows_2019-11766f2d-202008250946: TASK [Ensure chocolatey is installed with proxy] *******************************
windows_2019-11766f2d-202008250946: task path: /opt/packer/packer-templates/windows/roles/chocolatey/tasks/install.yaml:21
windows_2019-11766f2d-202008250946: [WARNING]: Chocolatey was missing from this system, so it was installed during
windows_2019-11766f2d-202008250946: changed: [192.168.22.162] => {"changed": true, "rc": 0, "stdout": "Upgrading the following packages:\r\nchocolatey\r\nBy upgrading you accept licenses for the packages.\r\nchocolatey|0.10.15|0.10.15|false\r\n\r\nChocolatey upgraded 0/1 packages. \r\n See the log for details (C:\\ProgramData\\Chocolatey\\logs\\chocolatey.log).\r\n", "stdout_lines": ["Upgrading the following packages:", "chocolatey", "By upgrading you accept licenses for the packages.", "chocolatey|0.10.15|0.10.15|false", "", "Chocolatey upgraded 0/1 packages. ", " See the log for details (C:\\ProgramData\\Chocolatey\\logs\\chocolatey.log)."]}
windows_2019-11766f2d-202008250946: this task run.
windows_2019-11766f2d-202008250946:
windows_2019-11766f2d-202008250946: TASK [chocolatey : Disable the default public source] **************************
windows_2019-11766f2d-202008250946: task path: /opt/packer/packer-templates/windows/roles/chocolatey/tasks/config.yaml:2
windows_2019-11766f2d-202008250946: fatal: [192.168.22.162]: FAILED! => {"changed": false, "msg": "Failed to find Chocolatey installation, make sure choco.exe is in the PATH env value"}
```

**Comment by gamethis** [comment]
On further investigation... it appears that the path is not registered until after a reboot.
adding the following to the playbook above results in a no change but choco sources still fails
```
- name: Ensure chocolatey path is registered
  win_path:
    name: PATH
    elements: C:\ProgramData\chocolatey\bin
    scope: machine
    state: present
```

There is no reboot required coming from win_chocolatey... but I find I have to reboot to get past the issue.
