### ISSUE TITLE
Allow multiple cannot be deselected

### ISSUE THREAD

**Issue by PhilippSelenium** [chocolatey/chocolatey-ansible#35]
this playbook task
```
- name: "Uninstall python version {{ uninstall_version }}"
    chocolatey.chocolatey.win_chocolatey:
      name: python3
      version: 3.6.8
      state: absent
      allow_multiple: false
      params: "/InstallDir:\\Python36"
```

results in the following command:
```
"command": "C:\\ProgramData\\chocolatey\\bin\\choco.exe uninstall python3 --yes --no-progress --limit-output --package-params /InstallDir:C:\\Python36 --timeout 2700 --allow-multiple --version 3.6.8"
```
1. Even though I explicitly deselected ```allow-multiple``` the command is executed with this flag
2. The default of ```allow-multiple``` is supposed to be ```false```: https://docs.ansible.com/ansible/latest/collections/chocolatey/chocolatey/win_chocolatey_module.html

ansible-version: 2.10.7
choco version : 0.10.5
