### ISSUE TITLE
Better FIPS mode support

### ISSUE THREAD

**Issue by opoplawski** [chocolatey/chocolatey-ansible#37]
An initial install of chocolatey with win_chocolatey fails on a FIPS mode machine with:
```
FIPS Mode detected - run 'choco feature enable -n useFipsCompliantChecksums' to use Chocolatey.
When FIPS Mode is enabled, Chocolatey requires useFipsCompliantChecksums feature also be enabled.
```
It would be helpful if there was a 'enable_fips_mode' or similar option to set this for the initial install.  Then it could be set permanently with win_chocolatey_feature.

**Comment by vexx32** [comment]
@ferventcoder if this is failing during the initial install of Chocolatey itself, how best can we handle that here to allow the initial install to complete?

**Comment by opoplawski** [comment]
To be more precise - chocolatey itself installs fine - and I'm able to then set the feature and install packages.  But the task in the playbook fails because it can't install any packages.

**Comment by vexx32** [comment]
Oh, okay, that makes things a bit easier then.

You may be able to workaround this for now by first adding a task to install `chocolatey` itself; this will be picked up by the module and handled the same way as the automatic chocolatey install is handled (although will respect specific requested versions etc, if any).

Then you can add the task to set the feature flag, followed by the rest of the package installs.

**Comment by opoplawski** [comment]
Thanks, that makes sense.  I'll try:
```yaml
- hosts: windows
  gather_facts: false
  tasks:
    - name: "Install chocolatey"
      win_chocolatey:
        name: chocolatey
        state: latest
    - name: "Configure chocolatey to be FIPS mode compliant"
      win_chocolatey_feature:
        name: useFipsCompliantChecksums
        state: enabled
```
