### ISSUE TITLE
[WARNING]: Chocolatey was missing from this system, so it was installed during this task run.

### ISSUE THREAD

**Issue by rgl** [chocolatey/chocolatey-ansible#40]
How to prevent the `[WARNING]: Chocolatey was missing from this system, so it was installed during this task run.` warning?

It seems there is no module to explicitly install chocolatey, or is it?

I would also want to pin its version.

**Comment by vexx32** [comment]
You can install Chocolatey itself in the normal fashion with `win_chocolatey`, specifying `chocolatey` as the package name to install and specifying a target version (if required) will override the automatic installation with that version and if memory serves that will bypass the warning. I think you should be able to specify to pin it just like any other package, and that pin operation should happen immediately after it's installed.

**Comment by rgl** [comment]
Does not seem to work:

```yaml

    - name: Install Chocolatey
      chocolatey.chocolatey.win_chocolatey:
        # https://community.chocolatey.org/packages/chocolatey
        name: chocolatey
        version: '0.10.15'
```

The warning is still displayed:

```
TASK [Install Chocolatey] ********************************************************************************
[WARNING]: Chocolatey was missing from this system, so it was installed during this task run.
changed: [10.17.3.2]
```
