### ISSUE TITLE
Upgrade of package when State is Present and Version is specified, fails unless forced

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-ansible#59]
Offending code:

```
if (-not $package_versions.Contains($version) -and -not $allow_multiple) {
                    $module.FailJson("Chocolatey package '$package' is already installed with version(s) '$($package_versions -join "', '")' but was expecting '$version'. Either change the expected version, set state=latest, set allow_multiple=yes, or set force=yes to continue")
} elseif ($version -notin $package_versions -and $allow_multiple) {
     # add the package back into the list of missing packages if installing multiple
     $missing_packages.Add($package) > $null
}
```

WORKAROUND: 

```yaml
- name: install Notepad++ at 7.6.3
  win_chocolatey:
    name: notepadplusplus
    version: 7.6.3
    allow_prerelease: yes
    state: latest
```
